{{ if or .Values.imagePuller.hook.enabled .Values.imagePuller.continuous.enabled }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: image-puller
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # make this daemonset temporary unless a continuous image puller is required
    {{ if .Values.imagePuller.continuous.enabled }}
    "helm.sh/hook-delete-policy": hook-succeeded
    {{ end }}
    # force this install/upgrade to run before the image-awaiter job
    "helm.sh/hook-weight": "-10"
  labels:
    app: jupyterhub
    component: image-puller
    release: {{ .top.Release.Name }}
    heritage: {{ .top.Release.Service }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
        app: jupyterhub
        component: image-puller
        release: {{ .top.Release.Name }}
        heritage: {{ .top.Release.Service }}
  template:
    metadata:
      labels:
        app: jupyterhub
        component: image-puller
        release: {{ .top.Release.Name }}
        heritage: {{ .top.Release.Service }}
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      initContainers:
      - name: image-pull-singleuser
        image: {{ .top.Values.singleuser.image.name }}:{{ .top.Values.singleuser.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
      {{ if not .top.Values.singleuser.cloudMetadata.enabled }}
      - name: image-pull-metadata-block
        image: {{ .top.Values.singleuser.networkTools.image.name }}:{{ .top.Values.singleuser.networkTools.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
      {{ end }}
      {{ range $k, $v := .top.Values.imagePuller.extraImages }}
      - name: image-pull-{{ $k }}
        image: {{ $v.name }}:{{ $v.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
      {{ end }}
      containers:
      - name: pause
        image: {{ .top.Values.imagePuller.pause.image.name }}:{{ .top.Values.imagePuller.pause.image.tag }}
{{- end }}
