# This job has a part to play in a helm upgrade process. It simply waits for the
# hook-image-puller daemonset which is started slightly before this job to get 
# its' pods running. If all those pods are running they must have pulled all the
# required images on all nodes as they are used as init containers with a dummy
# command.
{{ if .Values.imagePuller.hook.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: image-awaiter
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      restartPolicy: Never
      {{ if .Values.rbac.enabled }}
      serviceAccountName: image-awaiter
      {{- end }}
      containers:
        - image: {{ .Values.imagePuller.hook.image.name }}:{{ .Values.imagePuller.hook.image.tag }}
          name: image-awaiter
          imagePullPolicy: IfNotPresent
          command:
            - /image-awaiter
            - -ca-path=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - -auth-token-path=/var/run/secrets/kubernetes.io/serviceaccount/token
            - -api-server-address=https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT)
              # This is explicitly *not* quoted, since we are passing
              # This to a go program without any shell interpolation
            - {{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}

              {{ if not .Values.singleuser.cloudMetadata.enabled }}
            - {{ .Values.singleuser.networkTools.image.name }}:{{ .Values.singleuser.networkTools.image.tag }}
              {{ end }}
              {{ range $key, $value := .Values.imagePuller.extraImages }}
            - {{ $value.name }}:{{ $value.tag }}
              {{ end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{ end }}
